### ISSUE TITLE
External dart_format: Expected connection details in JSON but received plain text: "Can't load Kernel binary: Invalid kernel binary format version.\r"

### ISSUE THREAD

**Issue by DevEduu** [eggnstone/DartFormatJetbrainsPlugin#82]
Please supply any additional information here, e.g. the source code that caused the error:

```
StdErr: Can't load Kernel binary: Invalid kernel binary format version.
Did you install the dart_format package?
Basically just execute this:<pre>dart pub global activate dart_format</pre>
```
OS: Windows 11
Plugin version: 2.0.15
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Please try again with the latest version.
Is this fixed now?

**Comment by eggnstone** [comment]
This happens when Dart/Flutter is updated.
Updating Dart/Flutter manually and then restarting the IDE should help.
I'm looking for a better, permanent solution, therefore I'm keeping this issue open.

**Comment by gisborne** [comment]
I restarted the IDE and this is still happening.

FWIW, I got an error when I installed the plugin that it couldn't install the package? I think?

I installed it manually `dart pub global activate dart_format` but that didn't fix it.

I restarted the IDE; still not working.

Note that I installed all this after the 3.29 update.

**Comment by eggnstone** [comment]
Can you add the dart path to your path variable?
So that you can call dart from the commandline?

**Comment by gisborne** [comment]
My $PATH already contains /opt/homebrew/bin, which is where dart is, and I’ve been able to use it from the command line just fine, forever.

**Comment by eggnstone** [comment]
OK, that means that in the IDE a different $PATH is used, probably because of a different shell.

Can you attach the latest `DartFormatPlugin_...log` from your temp dir?

**Comment by gisborne** [comment]
I have no such file in my /tmp directory.

**Comment by eggnstone** [comment]
Can you look in `/var/tmp`, too?
Can you `echo $TMPDIR`?

**Comment by gisborne** [comment]
I have no such file in any of those 3 places.

**Comment by eggnstone** [comment]
This issue is referring to a different problem.
@gisborne: I moved your issue out to #128

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
